### ISSUE TITLE
fava Failed PUT /add_entries KeyError: 'tags'

### ISSUE THREAD

**Issue by penguinsam** [ALCC01/commercialista-bot#1]
I made a docker version of your piece successfully, but when I tried to add a new transaction, it shows:

`info startup Bot is up and running!
ERR! fava Failed PUT /add_entries KeyError: 'tags'`

Did I config something wrong?

**Comment by ALCC01** [comment]
Hi @penguinsam! Thanks for opening this issue. The internal API exposed by Fava changed in some of the latest updates. This should have been fixed in c1b1364, which is not included in 0.2.0 but will be part of a future release. You can build the bot against the latest commit and it should work (I have been testing it for a few weeks and should be stable). Let me know if you encounter any problem.

I'm also working on supporting docker on the [feat-docker](https://github.com/ALCC01/commercialista-bot/tree/feat-docker) branch if you want to check that out.

**Comment by penguinsam** [comment]
Hi @ALCC01, just tested our your docker branch on arm, I got the following error, trying to update my npm to see if ok

> commercialista-bot@0.2.0 watch
> nodemon --watch './**/*' --ext 'js,ts,json' --exec 'npm run dev'
sh: nodemon: not found

**Comment by ALCC01** [comment]
My guess is that you are trying to use the `docker-compose.yml` file which is not really suitable for deployment yet. The quick and dirty solution is to run `npm install` in your folder. Otherwise you can make the following changes and it should work.

```yml
...
 commercialista-bot:
    build:
      context: .
      target: builder
    command: npm run start
    restart: unless-stopped
    volumes:
      - ./shortcuts.json:/app/shortcuts.json:ro
...
```

I promise it will be easier once I have published a docker image and improved the docker compose config ;)
